grails-app/domain/teste/Banda.groovy
package teste

class Banda {

    String nome
    Genero genero

    static hasMany = [showsDaBanda:Show]

    static belongsTo = [Show]

    static constraints = {
        nome nullable: false, blank: false
    }

    static mapping = {
        table name:"bandas"
        showsDaBanda joinTable:
                [name: "bandas_e_show",
                 key:"id_banda",column: "id_show"];
    }

    enum Genero{
        ROCK("ROCK"), AXE("AXÉ"), FORRO("FORRÓ")

        private String descricao

        Genero(String descricao){
            this.descricao = descricao
        }

        String getDescricao() {
            return descricao
        }
    }

}

grails-app/domain/teste/Local.groovy
package teste

class Local {

    String nome
    Integer capacidade

    static hasMany = [showsNoLocal:Show]

    static constraints = {
        nome nullable: false, blank: false
        capacidade min: 0
    }

    static mapping = {
        table name:"locais"

    }

}

grails-app/domain/teste/Show.groovy
package teste

class Show {

    Date dataDoShow

    static belongsTo = [localDoShow:Local]

    static hasMany = [bandasNoShow:Banda]

    static constraints = {
        localDoShow nullable:false
    }

    static mapping = {
        table name:"shows"
        bandasNoShow joinTable:
                [name:"bandas_e_show",
                 key:"id_show",column:"id_banda"]
    }
}

grails-app/domain/teste/Teste.groovy
package teste

class Teste {

    String nome

    Date dataTeste

    Banda bandas

    List<Local> locaisList

    static constraints = {
    }
}

grails-app/controllers/teste/BandaController.groovy
package teste

class BandaController {

    def index() {

        def lista = Banda.list()

        render(view: "/banda/index", model:[bandas:lista])
    }

    def procurarPorNomeEGenero(){
        BandaService bandaService = new BandaService()

        String nomeBanda = params.nome

        def generos = params['listaGeneros[]']

       def lista = bandaService.findByNameAndGenero(nomeBanda, generos)

        render(template: "/banda/lista", model:[bandas:lista])
    }

    def prepararForm(){

        Banda novaBanda = new Banda()
        novaBanda.nome = ""

        render(template:"/banda/form", model:[banda:novaBanda])
    }

    def listar(){

        def lista = Banda.list()

        render(template: "/banda/lista", model:[bandas:lista])

    }

    def salvar(){
        BandaService bandaService = new BandaService()
        Banda banda = null

        if (params.id){
            banda = Banda.get(params.id)
        }else{
            banda = new Banda()
        }

        banda.nome = params.nome
        banda.genero = Banda.Genero.valueOf(params.genero)

        bandaService.save(banda)

        if(bandaService.hasErrors){
            render("Ops... deu pau!")
        }else{
           render("Salvo")
        }

    }

    def excluir(){
        Banda banda = Banda.get(params.id)
        BandaService bandaService = new BandaService()

        def listaDeShow = Show.list()

        bandaService.delete(listaDeShow,banda)

        def lista = Banda.list()
        render(template: "/banda/lista", model:[bandas: lista])
    }

    def alterar(){

        Banda banda = Banda.get(params.id)
        render(template:"/banda/form", model:[banda: banda])
    }
}

grails-app/controllers/teste/LocalController.groovy
package teste

class LocalController {

    def index() {

        def lista = Local.list()

        render(view:"/local/index", model:[locais:lista])
    }

    def listar(){

        def lista = Local.list()

        render(template: "/local/lista", model:[locais:lista])
    }

    def procurarPorNome(){
        LocalService localService = new LocalService()

        String nomeLocal = params.nome

        def lista = localService.findByName(nomeLocal)

        render(template: "/local/lista", model:[locais:lista])
    }

    def prepararForm(){

        Local novoLocal = new Local()
        novoLocal.nome = ""
        novoLocal.capacidade = 1

        render(template:"/local/form", model:[local:novoLocal])

    }

    def excluir(){
        Local local = Local.get(params.id)

        LocalService localService = new LocalService()
        localService.delete(local)

        def lista = Local.list()
        render(template: "/local/lista", model:[locais: lista])
    }

    def alterar(){

        Local local = Local.get(params.id)
        render(template:"/local/form", model:[local: local])
    }

    def salvar(){
        Local local = null

        if(params.id){
            local = Local.get(params.id)
        }else {
            local =  new Local();

        }

        String nomeLocal = params.nome
        Integer capacidadeDoShow = params.capacidade.toInteger()

        local.nome = nomeLocal
        local.capacidade = capacidadeDoShow

        LocalService localService = new LocalService()
        localService.save(local)

        if (localService.hasErrors){
            render("Ops... deu pau!")
        }else{
            render("Salvo")
        }

    }

}

grails-app/controllers/teste/ShowController.groovy
package teste

class ShowController {

    def index() {
        def lista = Show.list()

        render(view:"/show/index", model:[shows:lista])
    }

    def listar(){
        def lista = Show.list()

        render(template: "/show/lista",model: [shows: lista])
    }

    def prepararForm(){

        Show novoShow = new Show()
        novoShow.dataDoShow = new Date();

        def listaBandas = Banda.list()
        def listaLocais = Local.list()

        render(template:"/show/form", model:[show:novoShow,bandas:listaBandas, locais:listaLocais])

    }

    def alterar(){

        Show show = Show.get(params.id)

        def listaBandas = Banda.list()
        def listaLocais = Local.list()

        render(template:"/show/form", model:[show:show,bandas:listaBandas, locais:listaLocais])
    }


    def salvar(){

        Show show = null

        if(params.id){
            show = Show.get(params.id)
        }else{
            show = new Show()
        }

        Date dataShow = Date.parse("yyyy-MM-dd",params.dataShow)
        Local localDoShow = Local.get(params.localID)
        List listBandas = params.List_BandaIDs.toList()

        ShowService showService = new ShowService()

        showService.save(show,  dataShow, localDoShow, listBandas)

        if (showService.hasErrors){
            render("Ops... deu pau!")
        }else{
            render("Salvo")
        }
    }

    def excluir(){
        Show show = Show.get(params.id)

        ShowService showService = new ShowService()

        showService.delete(show)

        def lista = Show.list()
        render(template: "/show/lista", model:[shows: lista])
    }
}

grails-app/controllers/teste/TesteController.groovy
package teste

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class TesteController {

    TesteService testeService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond testeService.list(params), model:[testeCount: testeService.count()]
    }

    def show(Long id) {
        respond testeService.get(id)
    }

    def create() {
        respond new Teste(params)
    }

    def save(Teste teste) {
        if (teste == null) {
            notFound()
            return
        }

        try {
            testeService.save(teste)
        } catch (ValidationException e) {
            respond teste.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'teste.label', default: 'Teste'), teste.id])
                redirect teste
            }
            '*' { respond teste, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond testeService.get(id)
    }

    def update(Teste teste) {
        if (teste == null) {
            notFound()
            return
        }

        try {
            testeService.save(teste)
        } catch (ValidationException e) {
            respond teste.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'teste.label', default: 'Teste'), teste.id])
                redirect teste
            }
            '*'{ respond teste, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        testeService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'teste.label', default: 'Teste'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'teste.label', default: 'Teste'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/teste/UrlMappings.groovy
package teste

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(view:"/index")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

grails-app/views/teste/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'teste.label', default: 'Teste')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-teste" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-teste" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.teste}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.teste}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.teste}" method="POST">
                <fieldset class="form">
                    <f:all bean="teste"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/teste/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'teste.label', default: 'Teste')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-teste" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-teste" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.teste}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.teste}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.teste}" method="PUT">
                <g:hiddenField name="version" value="${this.teste?.version}" />
                <fieldset class="form">
                    <f:all bean="teste"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/teste/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'teste.label', default: 'Teste')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-teste" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-teste" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${testeList}" />

            <div class="pagination">
                <g:paginate total="${testeCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/teste/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'teste.label', default: 'Teste')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-teste" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-teste" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="teste" />
            <g:form resource="${this.teste}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.teste}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>